"""agregar precio total a envios maritimos y terrestres

Revision ID: ccab0e49dc56
Revises: 
Create Date: 2025-12-30 11:20:43.604817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ccab0e49dc56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_envios_terrestres_id'), table_name='envios_terrestres')
    op.drop_index(op.f('numero_guia'), table_name='envios_terrestres')
    op.drop_index(op.f('placa'), table_name='envios_terrestres')
    op.drop_table('envios_terrestres')
    op.drop_index(op.f('ix_bodegas_id'), table_name='bodegas')
    op.drop_table('bodegas')
    op.drop_index(op.f('ix_envios_preparados_id'), table_name='envios_preparados')
    op.drop_index(op.f('numero_guia'), table_name='envios_preparados')
    op.drop_table('envios_preparados')
    op.drop_index(op.f('ix_envios_maritimos_id'), table_name='envios_maritimos')
    op.drop_index(op.f('numero_flota'), table_name='envios_maritimos')
    op.drop_index(op.f('numero_guia'), table_name='envios_maritimos')
    op.drop_table('envios_maritimos')
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_puertos_id'), table_name='puertos')
    op.drop_table('puertos')
    op.drop_index(op.f('email'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_table('productos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('precio', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('telefono', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='clientes_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('email'), 'clientes', ['email'], unique=True)
    op.create_table('puertos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('ubicacion', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_puertos_id'), 'puertos', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.create_table('envios_maritimos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo_producto', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('cantidad', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_registro', sa.DATE(), nullable=True),
    sa.Column('fecha_entrega', sa.DATE(), nullable=True),
    sa.Column('puerto_entrega', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('precio_envio', mysql.FLOAT(), nullable=True),
    sa.Column('descuento', mysql.FLOAT(), nullable=True),
    sa.Column('numero_flota', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('numero_guia', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('cliente_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('envios_maritimos_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('numero_guia'), 'envios_maritimos', ['numero_guia'], unique=True)
    op.create_index(op.f('numero_flota'), 'envios_maritimos', ['numero_flota'], unique=True)
    op.create_index(op.f('ix_envios_maritimos_id'), 'envios_maritimos', ['id'], unique=False)
    op.create_table('envios_preparados',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('producto_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cantidad', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_recogida', sa.DATE(), nullable=True),
    sa.Column('puerto_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bodega_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cliente_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('precio_envio', mysql.FLOAT(), nullable=True),
    sa.Column('precio_productos', mysql.FLOAT(), nullable=True),
    sa.Column('descuento', mysql.FLOAT(), nullable=True),
    sa.Column('total', mysql.FLOAT(), nullable=True),
    sa.Column('numero_guia', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('numero_flota', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('placa', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('fecha_entrega', sa.DATE(), nullable=True),
    sa.Column('fecha_registro', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('numero_guia'), 'envios_preparados', ['numero_guia'], unique=True)
    op.create_index(op.f('ix_envios_preparados_id'), 'envios_preparados', ['id'], unique=False)
    op.create_table('bodegas',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('ubicacion', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_bodegas_id'), 'bodegas', ['id'], unique=False)
    op.create_table('envios_terrestres',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo_producto', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('cantidad', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_registro', sa.DATE(), nullable=True),
    sa.Column('fecha_entrega', sa.DATE(), nullable=True),
    sa.Column('bodega_entrega', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('precio_envio', mysql.FLOAT(), nullable=True),
    sa.Column('descuento', mysql.FLOAT(), nullable=True),
    sa.Column('placa', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('numero_guia', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('cliente_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('envios_terrestres_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('placa'), 'envios_terrestres', ['placa'], unique=True)
    op.create_index(op.f('numero_guia'), 'envios_terrestres', ['numero_guia'], unique=True)
    op.create_index(op.f('ix_envios_terrestres_id'), 'envios_terrestres', ['id'], unique=False)
    # ### end Alembic commands ###
