"""agregar total a envios maritimo y terrestre

Revision ID: d6270d8170fd
Revises: ccab0e49dc56
Create Date: 2025-12-30 12:44:11.911408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd6270d8170fd'
down_revision: Union[str, Sequence[str], None] = 'ccab0e49dc56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bodegas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('ubicacion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bodegas_id'), 'bodegas', ['id'], unique=False)
    op.create_table('envios_preparados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('fecha_recogida', sa.Date(), nullable=True),
    sa.Column('puerto_id', sa.Integer(), nullable=True),
    sa.Column('bodega_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('precio_envio', sa.Float(), nullable=True),
    sa.Column('precio_productos', sa.Float(), nullable=True),
    sa.Column('descuento', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('numero_guia', sa.String(length=10), nullable=True),
    sa.Column('numero_flota', sa.String(length=8), nullable=True),
    sa.Column('placa', sa.String(length=8), nullable=True),
    sa.Column('fecha_entrega', sa.Date(), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_guia')
    )
    op.create_index(op.f('ix_envios_preparados_id'), 'envios_preparados', ['id'], unique=False)
    op.create_table('envios_maritimos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_producto', sa.String(length=100), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=True),
    sa.Column('fecha_entrega', sa.Date(), nullable=True),
    sa.Column('puerto_entrega', sa.String(length=100), nullable=True),
    sa.Column('precio_envio', sa.Float(), nullable=True),
    sa.Column('descuento', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('numero_flota', sa.String(length=8), nullable=True),
    sa.Column('numero_guia', sa.String(length=10), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_flota'),
    sa.UniqueConstraint('numero_guia')
    )
    op.create_index(op.f('ix_envios_maritimos_id'), 'envios_maritimos', ['id'], unique=False)
    op.create_table('envios_terrestres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_producto', sa.String(length=100), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=True),
    sa.Column('fecha_entrega', sa.Date(), nullable=True),
    sa.Column('bodega_entrega', sa.String(length=100), nullable=True),
    sa.Column('precio_envio', sa.Float(), nullable=True),
    sa.Column('descuento', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('placa', sa.String(length=6), nullable=True),
    sa.Column('numero_guia', sa.String(length=10), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_guia'),
    sa.UniqueConstraint('placa')
    )
    op.create_index(op.f('ix_envios_terrestres_id'), 'envios_terrestres', ['id'], unique=False)
    op.drop_index(op.f('ix_puertos_id'), table_name='puertos')
    op.drop_table('puertos')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_table('productos')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_table('productos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('precio', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_table('puertos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('ubicacion', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_puertos_id'), 'puertos', ['id'], unique=False)
    op.drop_index(op.f('ix_envios_terrestres_id'), table_name='envios_terrestres')
    op.drop_table('envios_terrestres')
    op.drop_index(op.f('ix_envios_maritimos_id'), table_name='envios_maritimos')
    op.drop_table('envios_maritimos')
    op.drop_index(op.f('ix_envios_preparados_id'), table_name='envios_preparados')
    op.drop_table('envios_preparados')
    op.drop_index(op.f('ix_bodegas_id'), table_name='bodegas')
    op.drop_table('bodegas')
    # ### end Alembic commands ###
